### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by dstone42** [sgherbst/pyhigh#6]
I looked at another API to get this data, and it gives a slightly different elevation value than this package does. That API provided a resolution for how close the value will be to the true elevation. Is there a resolution for this package, or does it use a more accurate method?

Additionally, I appreciate the fix of the data source from the other issue that I commented on. The readme still has the old data source I believe, so the link to the description of the data source isn't good. It's not really that big of an issue, but I just thought I would let you know. I figured that out because I thought maybe the website for the data might have that resolution.

**Comment by sgherbst** [comment]
Good catch on the readme - just fixed that.

The data source is SRTM, which is described in [one place](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5296860/) as having 16m absolute accuracy at 90% confidence, with accuracy degrading with slope and elevation. pyhigh doesn't return a resolution for elevation queries, though.

In terms of tracking down discrepancies with other packages, one thing to look at would be how those packages estimate the elevation of coordinates that fall between samples in the dataset. pyhigh simply rounds to the nearest sample; other packages might use interpolation methods.

**Comment by dstone42** [comment]
Thank you! That answers all my questions!
